"""Emit the real sync bodies, by driving the real app.

The examples in the contract are generated by this, not written by hand. The app
track was burned once by a documented shape that did not match what the server
wanted, and a hand-maintained example drifts from the code the moment either
changes without the other. Regenerating is the check.

    python -m tools.contract_examples          # against a scratch database

Needs TEST_DATABASE_URL and ENCRYPTION_KEY, same as the test suite.
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
import uuid
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from httpx import ASGITransport, AsyncClient  # noqa: E402
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine  # noqa: E402

from app.db.session import Base  # noqa: E402
from tests.conftest import FakeGoogle, FakeRedis, make_settings  # noqa: E402
from app.main import create_app  # noqa: E402


def ms() -> int:
    return int(datetime.now(timezone.utc).timestamp() * 1000)


def show(title: str, payload) -> None:
    print(f"\n### {title}\n")
    print("```json")
    print(json.dumps(payload, indent=2, ensure_ascii=False))
    print("```")


async def main() -> None:
    url = os.environ["TEST_DATABASE_URL"]
    engine = create_async_engine(url)
    async with engine.begin() as conn:
        await conn.exec_driver_sql("CREATE SEQUENCE IF NOT EXISTS server_seq")
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

    app = create_app(make_settings())
    app.state.sessionmaker = async_sessionmaker(engine, expire_on_commit=False)
    app.state.redis = FakeRedis()
    app.state.google_verifier = FakeGoogle()

    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://x") as c:
        async def sign_in(subject):
            app.state.google_verifier.add(f"t-{subject}", subject, f"{subject}@example.com")
            r = await c.post("/v1/auth/google", json={
                "id_token": f"t-{subject}",
                "device": {"id": str(uuid.uuid4()), "platform": "android",
                           "app_version": "1.1.0"}})
            return r.json()

        owner = await sign_in("owner-example")
        caregiver = await sign_in("caregiver-example")
        oh = {"Authorization": f"Bearer {owner['access_token']}"}
        ch = {"Authorization": f"Bearer {caregiver['access_token']}"}

        t = ms()
        pid, mid, sid, did, eid = (str(uuid.uuid4()) for _ in range(5))

        push_body = {
            "changes": {
                "profiles": [{
                    "id": pid, "created_at": t, "updated_at": t, "deleted_at": None,
                    "name": "Mum", "color": 4283215696, "sort_order": 0,
                }],
                "medications": [{
                    "id": mid, "created_at": t, "updated_at": t, "deleted_at": None,
                    "profile_id": pid, "name": "Enalapril", "notes": None,
                    "dosage_text": "10 mg", "dose_amount": 1.0, "form": "tablet",
                    "pack_size": 30.0, "refill_threshold_days": 3, "is_active": True,
                    "photo_key": None,
                }],
                "schedules": [{
                    "id": sid, "created_at": t, "updated_at": t, "deleted_at": None,
                    "medication_id": mid, "type": "fixed_times",
                    "times": "[\"09:00\",\"21:00\"]", "days_of_week": None,
                    "interval_days": None, "start_date": "2026-08-01", "end_date": None,
                }],
                "dose_events": [{
                    "id": did, "created_at": t, "updated_at": t, "deleted_at": None,
                    "schedule_id": sid, "medication_id": mid, "profile_id": pid,
                    "planned_at": t, "status": "pending", "action_at": None,
                    "snooze_count": 0, "snoozed_until": None, "dose_amount": 1.0,
                }],
                "stock_events": [{
                    "id": eid, "created_at": t, "updated_at": t, "deleted_at": None,
                    "medication_id": mid, "delta": 30.0, "reason": "manual",
                    "dose_event_id": None,
                }],
            }
        }

        show("POST /v1/sync/push — тело", push_body)
        r = await c.post("/v1/sync/push", headers=oh, json=push_body)
        show("POST /v1/sync/push — ответ", r.json())

        # A record the caller has no right to send, to show the rejection shape.
        other = await sign_in("stranger-example")
        sh = {"Authorization": f"Bearer {other['access_token']}"}
        bad = await c.post("/v1/sync/push", headers=sh, json={"changes": {"medications": [
            {"id": str(uuid.uuid4()), "created_at": t, "updated_at": t, "deleted_at": None,
             "profile_id": pid, "name": "Not mine", "form": "tablet", "dose_amount": 1.0}
        ]}})
        show("POST /v1/sync/push — отказ по конкретной записи", bad.json())

        first = await c.get("/v1/sync/pull", headers=oh)
        show("GET /v1/sync/pull — ответ владельцу (без курсора: всё)", first.json())

        cursor = first.json()["cursor"]
        again = await c.get(f"/v1/sync/pull?cursor={cursor}", headers=oh)
        show("GET /v1/sync/pull?cursor=… — ничего нового", again.json())

        # Soft delete, to show how a removal crosses.
        gone = dict(push_body["changes"]["medications"][0])
        gone["updated_at"] = t + 60_000
        gone["deleted_at"] = t + 60_000
        await c.post("/v1/sync/push", headers=oh,
                     json={"changes": {"medications": [gone]}})
        deleted = await c.get(f"/v1/sync/pull?cursor={cursor}", headers=oh)
        show("GET /v1/sync/pull — как выглядит удаление", deleted.json())

        # Share the profile, then pull as the watcher.
        code = (await c.post("/v1/pairing/codes", headers=oh,
                             json={"profile_id": pid, "role": "with_alerts"})).json()["code"]
        await c.post("/v1/pairing/redeem", headers=ch, json={"code": code})
        watcher = await c.get("/v1/sync/pull", headers=ch)
        show("GET /v1/sync/pull — ответ наблюдателю (та же выборка)", watcher.json())

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
